// Données complètes du Bénin - Départements et Communes

export const beninLocations = {
  "Littoral": [
    "Cotonou",
    "Ouidah",
    "Abomey-Calavi",
    "Allada",
    "Kpomassè",
    "Tori-Bossito",
    "Sè",
    "Comé",
    "Grand-Popo",
    "Athiémé",
  ],
  "Atlantique": [
    "Porto-Novo",
    "Aguégués",
    "Adjarra",
    "Adjohoun",
    "Dangbo",
    "Ganvié",
    "Ifangni",
    "Ketou",
    "Avrankou",
    "Déssalines",
    "Sakété",
  ],
  "Ouémé": [
    "Adanwomé",
    "Adja-Ouèrè",
    "Akodeha",
    "Avrankou",
    "Azowé",
    "Dangbo",
    "Demokoe",
    "Ganvié",
    "Houédomè",
    "Ifangni",
    "Iworé",
    "Kétou",
    "Onigbolo",
    "Padda",
    "Sèmèkpo",
    "Totchè",
    "Zagnanado",
  ],
  "Plateau": [
    "Adohoun",
    "Adjanon",
    "Adjarra",
    "Adjohoun",
    "Affon",
    "Agbangnizoun",
    "Agoué",
    "Agué",
    "Agué-Gare",
    "Agué-Ville",
  ],
  "Mono": [
    "Athiémé",
    "Bopa",
    "Comé",
    "Dékanmey",
    "Demè",
    "Gnanhouizoun",
    "Grand-Popo",
    "Houéyogbé",
    "Lokossa",
    "Sèmè-Kpodji",
    "Toviklin",
    "Vogan",
  ],
  "Couffo": [
    "Aplahoué",
    "Djakotomey",
    "Dogbo",
    "Klouekanmey",
    "Lalo",
    "Lavé",
    "Lokossa",
    "Toviklin",
    "Zagnanado",
    "Zemidjan",
  ],
  "Zou": [
    "Abomey",
    "Agbangnizoun",
    "Agoué",
    "Agué",
    "Agué-Gare",
    "Agué-Ville",
    "Aplahoué",
    "Bohicon",
    "Cové",
    "Djakotomey",
    "Dogbo",
    "Djidja",
    "Kpomassè",
    "Ouinhi",
    "Savè",
    "Zagnanado",
    "Zangnon",
  ],
  "Collines": [
    "Dassa-Zoumé",
    "Glazoué",
    "Ouèssè",
    "Savalou",
    "Savè",
    "Bantè",
    "Kilibo",
  ],
  "Borgou": [
    "Alibori",
    "Banikoara",
    "Bembèrèkè",
    "Bétérou",
    "Boukoumbé",
    "Gorou",
    "Karimama",
    "Kandi",
    "Kassakou",
    "Katialé",
    "Niki",
    "Nodjirou",
    "Parakou",
    "Ségérèga",
    "Sinendé",
    "Sunli",
    "Ternon",
  ],
  "Alibori": [
    "Banikoara",
    "Gaya",
    "Kandi",
    "Karimama",
    "Malanville",
    "Niki",
    "Segueré",
    "Sontoukoura",
  ],
  "Atakora": [
    "Boukoumbé",
    "Cobly",
    "Comendakha",
    "Copargo",
    "Djougou",
    "Granhoué",
    "Jougou",
    "Kérou",
    "Kouandé",
    "Manta",
    "Matéri",
    "Nattingou",
    "Olougbadé",
    "Ouary",
    "Ouarèye",
    "Péhunco",
    "Pénéssoulou",
    "Samarou",
    "Taibarou",
    "Taminani",
    "Tanugan",
    "Tassouguè",
    "Toukountouna",
    "Yendé",
  ],
  "Donga": [
    "Bassila",
    "Birni",
    "Djougou",
    "Gogounou",
    "Jougou",
    "Ouaké",
  ],
};

export const getDepartements = () => Object.keys(beninLocations);

export const getCommunes = (departement) => {
  return beninLocations[departement] || [];
};
